name: Publish feature
on:
  pull_request:
  release:
    types: published
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  publish-feature:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: devcontainers-community/publish-feature@v1
        with:
          image: ghcr.io/alexdenisov/features/feature-cmake
          files: |
            common/install.sh
            common/utilities.sh
            common/etc/bash.bash_env
            install.sh
            README.md
            devcontainer-feature.json
            LICENSE
            test.sh
